// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"GoGF/app/model/internal"
)

// Student is the golang structure for table student.
type Student internal.Student

// Fill with you ideas below.
