// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"GoGF/app/model/internal"
)

// ToolTPartnerInfo is the golang structure for table t_partner_info.
type ToolTPartnerInfo internal.ToolTPartnerInfo

// Fill with you ideas below.
