// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"GoGF/app/model/internal"
)

// ToolTLogThirdCallback202104 is the golang structure for table t_log_third_callback_202104.
type ToolTLogThirdCallback202104 internal.ToolTLogThirdCallback202104

// Fill with you ideas below.
