// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"GoGF/app/model/internal"
)

// ToolTLocalCacheWhitelist is the golang structure for table t_local_cache_whitelist.
type ToolTLocalCacheWhitelist internal.ToolTLocalCacheWhitelist

// Fill with you ideas below.
