// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Student is the golang structure for table student.
type Student struct {
	Id   int    `orm:"id,primary" json:"id"`   //
	Name string `orm:"name"       json:"name"` //
	Sex  string `orm:"sex"        json:"sex"`  //
	Age  int    `orm:"age"        json:"age"`  //
}
