// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// ToolTPartnerInfo is the golang structure for table t_partner_info.
type ToolTPartnerInfo struct {
	Id           int         `orm:"id,primary"    json:"id"`           //
	PartnerId    string      `orm:"partner_id"    json:"partnerId"`    //
	AesKey       string      `orm:"aes_key"       json:"aesKey"`       //
	AesIv        string      `orm:"aes_iv"        json:"aesIv"`        //
	PartnerToken string      `orm:"partner_token" json:"partnerToken"` //
	Ctime        *gtime.Time `orm:"ctime"         json:"ctime"`        //
}
