// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// ToolTLocalCacheWhitelist is the golang structure for table t_local_cache_whitelist.
type ToolTLocalCacheWhitelist struct {
	Id          int         `orm:"id,primary"   json:"id"`          //
	UserName    string      `orm:"user_name"    json:"userName"`    //
	UserMobile  string      `orm:"user_mobile"  json:"userMobile"`  //
	UserIdcard  string      `orm:"user_idcard"  json:"userIdcard"`  //
	Cdate       *gtime.Time `orm:"cdate"        json:"cdate"`       //
	Ctime       *gtime.Time `orm:"ctime"        json:"ctime"`       //
	ChannelType string      `orm:"channel_type" json:"channelType"` //
}
