# HTTP Server
[server]
Address = ":8199"
ServerRoot = "public"
ServerAgent = "gf-app"
LogPath = "public/log/ServerLog"
ErrorLogPattern = "error-{Y-m-d}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
AccessLogEnabled = true              # 是否记录访问日志。默认为false
AccessLogPattern = "access-{Y-m-d}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"
SessionIdName = "sessionId"
SessionPath = "public/log/session"
SessionMaxAge = "24h"

# Logger.
[logger]
Path = "public/log/test"
file = "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"
Level = "all"
Stdout = true
RotateSize = "200M"
RotateBackupExpire = "7d"
[logger.error]
Path = "public/log/error"
file = "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"

# Template.
[viewer]
Path = "template"
DefaultFile = "index.html"
Delimiters = ["${", "}"]

# Database.
[database]
[[database.default]]
link = "mysql:root:root@tcp(127.0.0.1:3306)/gf-test"
debug = true
[[database.cogito_tool]]
link = "mysql:loan_api:loan@123456@tcp(47.244.165.169:3306)/db_cogito_tool"
debug = true
#dryRun = true
# Database logger.
[database.logger]
Path = "public/log/db"
Level = "all"
Stdout = true
#redis
[redis]
default = "127.0.0.1:6379,0,root"

#gfcli
[gfcli]
[[gfcli.gen.dao]]
link = "mysql:root:root@tcp(127.0.0.1:3306)/gf-test"
tables = "user,student"
[[gfcli.gen.dao]]
link = "mysql:loan_api:loan@123456@tcp(47.244.165.169:3306)/db_cogito_tool"
tables = "t_local_cache_whitelist,t_partner_info,t_log_third_callback_202104"