// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"GoGF/app/dao/internal"
)

// studentDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type studentDao struct {
	internal.StudentDao
}

var (
	// Student is globally public accessible object for table student operations.
	Student = studentDao{
		internal.Student,
	}
)

// Fill with you ideas below.
