// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"GoGF/app/dao/internal"
)

// toolTLocalCacheWhitelistDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type toolTLocalCacheWhitelistDao struct {
	internal.ToolTLocalCacheWhitelistDao
}

var (
	// ToolTLocalCacheWhitelist is globally public accessible object for table t_local_cache_whitelist operations.
	ToolTLocalCacheWhitelist = toolTLocalCacheWhitelistDao{
		internal.ToolTLocalCacheWhitelist,
	}
)

// Fill with you ideas below.
