// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"GoGF/app/dao/internal"
)

// toolTPartnerInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type toolTPartnerInfoDao struct {
	internal.ToolTPartnerInfoDao
}

var (
	// ToolTPartnerInfo is globally public accessible object for table t_partner_info operations.
	ToolTPartnerInfo = toolTPartnerInfoDao{
		internal.ToolTPartnerInfo,
	}
)

// Fill with you ideas below.
