// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"GoGF/app/dao/internal"
)

// toolTLogThirdCallback202104Dao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type toolTLogThirdCallback202104Dao struct {
	internal.ToolTLogThirdCallback202104Dao
}

var (
	// ToolTLogThirdCallback202104 is globally public accessible object for table t_log_third_callback_202104 operations.
	ToolTLogThirdCallback202104 = toolTLogThirdCallback202104Dao{
		internal.ToolTLogThirdCallback202104,
	}
)

// Fill with you ideas below.
